dist: trusty
services: docker
sudo: required

language: rust
rust:
  - beta

env:
  global:
    - CRATE_NAME=twitchdl

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx
    # Windows
    - env: TARGET=x86_64-pc-windows-gnu

notifications:
  email: false

branches:
  only:
    - master

cache: cargo

before_cache:
  - rm -rfv target/$TARGET/release/incremental/$CRATE_NAME-*
  - rm -rfv target/$TARGET/release/.fingerprint/$CRATE_NAME-*
  - rm -rfv target/$TARGET/release/build/$CRATE_NAME-*
  - rm -rfv target/$TARGET/release/deps/$CRATE_NAME-*
  - rm -rfv target/$TARGET/release/$CRATE_NAME.d
  - cargo clean -p $CRATE_NAME

before_install:
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/build.sh

after_success:
  - files=$(ls target/$TARGET/release)
  - echo $files

before_deploy:
  - export RELEASE_NAME=`date +%m.%d`"."`echo $TRAVIS_COMMIT | cut -c 1-16`
  - bash ci/before_deploy.sh

deploy:
  name: $RELEASE_NAME
  body: Automatically generated by Travis CI
  prerelease: true
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GXyK0XMxp/d7QmpnkPb6Ltacb9BSgK8cFU46dELfQF7Xn7h76XBlOjjUZAm/FqJopkLV/qpLjumvztYF+Zy3NLromhDkWazc7lSum3aJ86cuJBJTQrwH27qZqsIiz8QtYJIOBXIttTE5PCdPsyr3/KFmVcyRTAnTd+ORjPNTAJKOMwVW3PQwVOP2r+Gnxap0NACkwLwmW5xBTMhOGsyA/McnC19cYG7782IPMgLcvnNMbshfT5HL204XZxZeysvVJBApJ4G+hTUaYkgylc32oOtF0QNQbE2hG+PMmbzE+HqJwa9YeH+5RmrvL+hLbNMYcFNGwnJ+y4QA82qIdWtvgxpOW8+WuQUh6oiOCTD4yglsrRHKNpg5n2sSBqnvPslwM0feQ5aMZZWNxLeSFlTiQVMrY777od+aQh6sKaFLEg7OrSo1KEkDL4IgqOSlnyp9Cd5i+f+t8NJjcvrU9yBUe6JmO1AaSObIgX5BEB9u7kSWRnbjX5mU1ROlhfDbjcV4fEKeB+zzb/VYmclXMpehGmsH7hU16taU0MMS1FFClj9LD7M0bqCGRfkyUtB1jImp2uEELXJMjQCbGmZz19SnDTjFKSe7zwQYsgpntx5uNMSQD2WjHPl6/SQpADA1BYsH4hIInwjjL56SsV312KWgqSoxFNrtkgHNw28ZGky5Yfg=
  file:
    - $CRATE_NAME-$TARGET-RELEASE.zip
    - $CRATE_NAME-$TARGET-DEBUG.zip
  on:
    repo: sylingd/TD
    tags: false